### ISSUE TITLE
Crashes alot

### ISSUE THREAD

**Issue by ziphyfyi** [unlegitdev/Discord-Webhook-Sender#1]
I could only use it once now it crashes when entering information

**Comment by unlegitdev** [comment]
Hi Carson,
thank you for your report, i am sorry for that Problem and will immedially try to fix this issue


________________________________
Von: Carson <notifications@github.com>
Gesendet: Wednesday, April 15, 2020 8:36:39 PM
An: unlegitdev/Discord-Webhook-Sender <Discord-Webhook-Sender@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Betreff: [unlegitdev/Discord-Webhook-Sender] Crashes alot (#1)


I could only use it once now it crashes when entering information

**Comment by unlegitdev** [comment]
I found and fixed the issue. The app should now run without any problems.
